name: large_file_experiment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pyarrow
  - pandas
  - pyyaml
  - snowflake-snowpark-python
  - pip
  - pip:
    - "snowflake-connector-python[secure-local-storage,pandas]"
    - snowflake
