file:
  records: 5_000
  database: gewurztraminer
  schema: bronze
  stage: landing_zone
  table: levure
  fields:
  - field:
        name: Field01
        type: date
        length: 8
  - field:
        name: Field02
        type: string
        length: 10
  - field:
        name: Field03
        type: string
        length: 25
  - field: 
        name: Field04
        type: integer
        length: 10
  - field:
        name: Field05
        type: date
        length: 8
  - field:
        name: Field06
        type: string
        length: 4
test:
  records: 1_000
  database: pinot_noir
  schema: bronze
  stage: landing_zone
  table: bouchon
  fields:
  - field: 
        name: Field_x1
        type: integer
        length: 4
  - field:
        name: Field_x2
        type: string
        length: 100
